---
- name: Check Current Time Zone
  shell: cat /etc/timezone
  register: current_zone
  changed_when: current_zone.stdout != timezone

- name: Set Time Zone Variables
  copy: content={{timezone}}
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  when: current_zone.stdout != timezone
  notify:
    - Update Time Zone
